CREATE schema LEADSADMIN;

CREATE TABLE LEADSADMIN.USERS(id IDENTITY PRIMARY KEY, name VARCHAR(255), notes VARCHAR(255));

DROP TABLE LEADSADMIN.TICKETS;

CREATE TABLE LEADSADMIN.TICKETS(id IDENTITY PRIMARY KEY, userid VARCHAR(50), system VARCHAR(50) , description VARCHAR(100), status VARCHAR(20), created TIMESTAMP DEFAULT NOW(), updated TIMESTAMP DEFAULT NOW());

 