CREATE schema LEADSADMIN;

CREATE TABLE LEADSADMIN.USERS(id IDENTITY PRIMARY KEY, name VARCHAR(255), notes VARCHAR(255));

CREATE TABLE LEADSADMIN.TICKETS(id IDENTITY PRIMARY KEY, userid VARCHAR(25), description VARCHAR(80), status VARCHAR(20), created TIMESTAMP DEFAULT NOW(), updated TIMESTAMP DEFAULT NOW());
